# Generated by Django 4.1.7 on 2023-04-10 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authcart", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Orders",
        ),
        migrations.DeleteModel(
            name="OrderUpdate",
        ),
    ]
