# Generated by Django 4.1.7 on 2023-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materials",
            fields=[
                ("material_id", models.AutoField(primary_key=True, serialize=False)),
                ("material_name", models.CharField(max_length=200)),
                ("category", models.CharField(default="", max_length=200)),
                ("subcategory", models.CharField(default="", max_length=200)),
                ("desc", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images/images")),
            ],
        ),
    ]
