# Generated by Django 4.1.7 on 2023-04-03 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0002_materials"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Materials",
            new_name="Product",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="material_id",
            new_name="product_id",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="material_name",
            new_name="product_name",
        ),
    ]
