# Generated by Django 4.1.7 on 2023-04-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0004_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.AutoField(default="", primary_key=True, serialize=False),
        ),
    ]
