# Generated by Django 4.1.7 on 2023-04-10 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0007_orders_orderupdate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="orders",
        ),
        migrations.DeleteModel(
            name="OrderUpdate",
        ),
    ]
